### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by kliebes** [jekuno/milia#28]
I recently ran into an issue where I wasn't sure if my validations against a tenanted model was working correctly.

When I was using the following code:

```
validates_uniqueness_of :name
```

The model would not save a record  with a name that had an identical name to another record which was under a different tenant. So for example if I had a record were name = joe and tenant_id = 1. Then I went in under tenant #2 and tried to save another record with name = joe, it would not save and say the name had to be unique. I ended up using the following validation to fix it.

```
validates_uniqueness_of :name, :scope => :tenant_id
```

My question is just is this the correct way to handle unique validation with milia, or did I bork something in my application and shouldn't need the :scope => :tenant_id part? If I did screw something up, do you have any pointers on where to start looking?

FYI, everything else "seems" to operate as expected. Here is the first part of my model code just for your info.

```
class Plan < ActiveRecord::Base
  #sets up model as a tenant in milia
  acts_as_tenant

  has_many :donations
        attr_accessible :stripe_plan_id, :name, :summary, :title, :amount

  validates :amount, presence: true
  validates_uniqueness_of :name, :scope => :tenant_id, :case_sensitive => false
  validates :name, presence: true
  validates :stripe_plan_id, presence: true, uniqueness: { case_sensitive: false }
  validates :summary, presence: true
  validates_uniqueness_of :summary, :scope => :tenant_id, :case_sensitive => false
```

Second FYI, I was installing the AASM gem at the time too (though I did uninstall AASM to make sure it wasn't causing the issue). I saw you had AASM experience too and just wondered if you had seen any conflicts between AASM and Milia.

Thanks, any of your thoughts will be appreciated.

**Comment by cseelus** [comment]
@kliebes Did you find out was caused Example 1 not to work? I ran into the same problem.
