### ISSUE TITLE
Rails 4.1 compatibility

### ISSUE THREAD

**Issue by klippx** [jekuno/milia#37]
Hello,

When do you plan to release milia to be fully Rails 4.1 compatible?

We are upgrading to latest version of Rails, and the next step of our application will be to find a suitable multi tenancy gem. Currently, a con with this gem is the current Rails 4.0.x dependency.

Since this dependency is due to the web-app-theme, namely `rails g web_app_theme:milia`, and I plan to incorporate this into an existing application (not running the command at all) then I should be able to safely ignore the 4.0.x dependency by forking that gem and loosening the gemspec as per https://github.com/dsaronin/milia/issues/34 - Am I correct?

Best regards,
Mathias

**Comment by jekuno** [comment]
As of now Milia works with 4.1, 4.2 and (nearly) Rails 5 as well.
