### ISSUE TITLE
Delete a tenant

### ISSUE THREAD

**Issue by ohadco** [jekuno/milia#44]
Hi,
When I delete tenant, the user, member and all it's records is still in the DB.
I have added to tenants.rb model:
`has_many :members, dependent: :destroy`
`has_many :all_other_models_acts_as_tenants, dependent: :destroy`

I'm working with postgresql.
I deleted the tenant from rails console and also directly from the pg-Admin gui.
also tried to delete the member, the user etc.

So my question is what is the way to delete Tenant with all it's associated records?

Thanks!

**Comment by cseelus** [comment]
When destroying a tenant while using Postgres, it fails for tenanted models which already have tenanted records:

`ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "tenants" violates foreign key constraint "fk_rails_xyz" on table "members"
DETAIL:  Key (id)=(1) is still referenced from table "members".
: DELETE FROM "tenants" WHERE "tenants"."id" = $1`

I also tested this with a vanilla Sample Milia App (with `pg` added to the gems and adapted `database.yml` of course). May be related to [Rails issue 12380](https://github.com/rails/rails/issues/12380).

**Comment by jekuno** [comment]
Either destroy all members before destroying a tenant or add the following to `tenant.rb`:
`has_many :members,        dependent: :destroy`

Hope this helps!

**Comment by jekuno** [comment]
Closing it for now. Feel free to add a note if you still have questions.

**Comment by yshmarov** [comment]
I did everything as taught above (`has_many :members, dependent: :destroy`), and when I want to destroy I get:
```
D, [2019-07-18T21:41:30.079987 #4] DEBUG -- :   Tenant::HABTM_Users Destroy (1.1ms)  DELETE FROM "tenants_users" WHERE "tenants_users"."tenant_id" = $1  [["tenant_id", 25]]
D, [2019-07-18T21:41:30.084174 #4] DEBUG -- :   Tenant Destroy (3.8ms)  DELETE FROM "tenants" WHERE "tenants"."id" = $1  [["id", 25]]
D, [2019-07-18T21:41:30.085450 #4] DEBUG -- :    (1.1ms)  ROLLBACK
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "tenants" violates foreign key constraint "fk_rails_4e4771d44b" on table "members")
DETAIL:  Key (id)=(25) is still referenced from table "members".
: DELETE FROM "tenants" WHERE "tenants"."id" = $1
```
