### ISSUE TITLE
Milia and dashing-rails (engine) integration

### ISSUE THREAD

**Issue by testflyjets** [jekuno/milia#45]
I'm trying to sort out how to integrate dashing-rails, which provides a Rails engine of Shopify's Dashing dashboard framework, into a Milia-enabled app.

https://github.com/gottfrois/dashing-rails

In general, what should be required to use an engine with Milia?  Setting the current tenant seems like an obvious requirement but I'm unsure of how or where to do that when using an engine.  Any tips?

**Comment by jekuno** [comment]
With engines everything works the same as you are already used to.
In your engine simply setup your tenanted models as usual (adding a `tenant` reference in your engine migrations to those models and adding `acts_as_tenant` to your model file). That's it!
