### ISSUE TITLE
Recapcha & ENV Locations

### ISSUE THREAD

**Issue by andhofmt** [jekuno/milia#48]
Hello,

I couldn't seem to find where the option to disable Recapcha was.
Also, I didn't find the location of the ENV variables in the documenation. I assumed maybe an application.yml? 

Any help appreciated.

**Comment by dsaronin** [comment]
Environment variable are part of your operating system environment. The
document gives examples for a linux system.
Recaptcha is disabled via the config/initializers/milia.rb file.

**Comment by andhof-mt** [comment]
Oh, sounds good to me.

Is there anything I should be aware of if I want to use a gem like Figaro for ENV variables?

**Comment by dsaronin** [comment]
I don't know anything about Figaro.
Whatever you do, however, the variables need to be accessible from within
the app as ENV[ variable-name ].

**Comment by jekuno** [comment]
Nothing special to be aware of when using Figaro. :)
