### ISSUE TITLE
Default Scopes

### ISSUE THREAD

**Issue by jp7jp** [jekuno/milia#49]
Is it right to say that "Rails 3.2 onwards, the last designated default scope overrides any prior scopes and will invalidate multi-tenanting"? Rails docs says "If you use multiple default_scope declarations in your model then they will be merged together". I tested it myself:

```
class Article < ActiveRecord::Base
  acts_as_tenant
  default_scope {
    where("created_at > '2015-01-01'")
  }
end
```

Console:

```
Tenant.set_current_tenant(1)
Article.all
SELECT "articles".* FROM "articles" WHERE (articles.tenant_id = 1) AND (created_at > '2015-01-01')
```

**Comment by dsaronin** [comment]
My understanding is that the last-used default_scope overrides anything
else. Milia won't work in those situations.

**Comment by jekuno** [comment]
I agree with @jp7jp.

From http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope:
> If you use multiple default_scope declarations in your model then they will be merged together. This is also the case with inheritance and module includes where the parent or module defines a default_scope and the child or including class defines a second one.

We should prove this with some scoping tests and remove the according warning from the Readme.

**Comment by jekuno** [comment]
Added according info on default_scopes to https://github.com/jekuno/milia/blob/rails5-support/README.md
