### ISSUE TITLE
Doing a global admin panel

### ISSUE THREAD

**Issue by philsmy** [jekuno/milia#62]
This is not so much an issue as a plea for guidance! We have a nicely working multi-tenanted site, but, how can we write back-end admin tools that let us see data across all tenants? Something like rails_admin.
Has anyone done this or can point to what to do?
Maybe adding a user to all tenants?

Tips appreciated!

**Comment by dsaronin** [comment]
Yes, I do that all the time, primarily using both rake tasks and the rails
console. I believe that the README covers that and gives examples from what
I use, towards the end of the README.

**Comment by cseelus** [comment]
@philsmy You could define certain users as admins (you'll find lots of help how to do this with Devise) and assign these users to new tenants upon tenant creation, so that they will have access to all of your applications accounts, e.g. in `tenant.rb` inside `self.tenant_signup`:

```ruby
# Assign this tenant to all the admins as well
User.admins.each do |admin|
  admin.tenants.push(tenant)
end
```

**Comment by philsmy** [comment]
Funnily enough thats exactly what we ended up doing.

On 23 August 2015 at 11:42, Chris Seelus <notifications@github.com> wrote:

> @philsmy <https://github.com/philsmy> You could define certain users as
> admins (you'll find lots of help how to do this with Devise) and assign
> these users to new tenants upon tenant creation, so that they will have
> access to all of your applications accounts, e.g. in tenant.rb inside
> self.tenant_signup:
>
> # Assign this tenant to all the admins as wellUser.admins.each do |admin|
>   admin.tenants.push(tenant)end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsaronin/milia/issues/62#issuecomment-133776152>.
>



-- 
Phil Smy - "http://www.philsmy.com"
filmsite: http://philsfilmlinks.com
twitter: http://twitter.com/psmy
facebook: http://facebook.com/philsmy

**Comment by yshmarov** [comment]
Phil, could you please give some more perspective on how you acomplished it?

**Comment by jekuno** [comment]
@philsmy Nice that you found a solution. Enjoy your time!
