### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by jekuno** [jekuno/milia#64]
Did you test `milia` with Rails 5 already or do you have plans to do so?

**Comment by dsaronin** [comment]
I have not tested milia on Rails 5. We should probably try to find
interested people to help with milia maintenance, as I am retired now from
software development.

**Comment by jekuno** [comment]
@MatthewMarkgraaff @julienroger @epoplavskis @2point0concepts @dearty @kylegraydev @pineapplethief
All of you forked milia and worked towards using it with Rails 5. Does anybody of you already use milia with Rails5? This would be a great help for many people who use milia and want to switch to Rails5.

_Please drop a short note in this thread!_

**Comment by pineapplethief** [comment]
@jekuno I hadn't tested it thoroughly, but it seems to work after you bump activerecord and devise versions to be compatible with rails 5

**Comment by MatthewMarkgraaff** [comment]
@jekuno Hey there. Unfortunetely I didn't get too far with it but if I get some time I'll take a look. Try @pineapplethief suggestions and let us know how it goes.

**Comment by dsaronin** [comment]
I'm retired now and looking for someone to take over the Milia project...
Any volunteers?

**Comment by jekuno** [comment]
I like the project and it looks as if the only other popular row based multi tenanting gem`acts_as_tenant` has been put on ice as well (https://github.com/ErwinM/acts_as_tenant/issues/152#issuecomment-269588618).

So even as I'm quite busy right now I might jump into keeping `milia` alive if we find more developers willing to participate.

**Comment by dsaronin** [comment]
That would be awesome. My design philosophy has always been simplicity and
combinatorial basic features like Lego blocks; not trying to meet every use
case, only the most common 80%. You'll find some users trying to pull the
project in all kinds of directions.

**Comment by jekuno** [comment]
Sounds good - simplicity is important to keep `milia` maintainable in long term. My first goal would be to ensure Rails 5 compatibility. Can I reach you via your majozi email address so we can talk about some details?

**Comment by dsaronin** [comment]
use dsaronin@gmail.com please.

**Comment by epoplavskis** [comment]
hey @jekuno, we at @2point0concepts got milia working with rails 5 just by updating the gemspec file, and have been using it for a few months now in one of our major projects without an issue. 
https://github.com/2point0concepts/milia

**Comment by jekuno** [comment]
@pineapplethief @MatthewMarkgraaff @epoplavskis Thanks for your responses. I also tested `milia` with Rails 5 during the past two days and could turn all of my tests green with just a few adaptions. You can see the changes in https://github.com/jekuno/milia/tree/rails5-support. As soon as I finished the work the changes will most probably find their way back to the milia gem.

**Comment by runyourgym** [comment]
Thanks for the work you guys are doing. Since you've already walked the walk, I figured I would ask: after upgrading, I've noticed that when I add a staff member, it sends out the "password changed" email instead of the "confirmation" email. The new user is still getting added to the DB properly and no errors are getting thrown - it just seems to be sending the wrong email. Additionally, the flash message about adding a new member can't seem to find the new user's email address from here:

`flash[:notice] = "New Staff Member Invited (#{@user.email})!"`

Anything obvious I might be overlooking?

**Comment by dsaronin** [comment]
Kuno, my first guess would be that Devise, again, has changed its API
slightly, probably the callback after a new member is created.

**Comment by jekuno** [comment]
@runyourgym Did you upgrade using the branch https://github.com/jekuno/milia/tree/rails5-support? Can you confirm that the flash message contained the email address before updating? Which devise version do you use now and which before?

**Comment by runyourgym** [comment]
Thanks for the replies @dsaronin and @jekuno. I'm doing the upgrade on a separate branch, my master branch (identical except for the Rails 5 upgrade) still works perfectly. That was my first thought too (that it got messed up previously), but it doesn't seem to be the case.

I was on Devise 3.5.10 prior to the upgrade, and am now on 4.2.0.

Thanks so much for any assistance.

Matt

**Comment by jekuno** [comment]
@runyourgym Hunting on that issue right now. Can you provide any additional info already?

@dsaronin When inviting a new member `save_and_invite_member` from milia gets called which basically does a `user.save`. Am I right that you expect this to trigger a callback which sends an invitation? It seems as if this doesn't happen.
I had a look at `devise_invitable 1.7`. It contains a`Devise::InvitationsController` which has a create action that calls `invite_resource` (which sends an invitation mail).
Alternatively `devise_invitable` also allows for calling `user.invite!` directly which sends an invitation.
What would be the most elegant way to reenable sending invitations?

**Comment by runyourgym** [comment]
@jekuno No additional information at this time, I reconfirmed that the Rails version was indeed what initiated the bug but other than that I'm not sure what's causing it to fail.

**Comment by dsaronin** [comment]
Kuno, well this is the problem I've always had with devise: the API is
never stable. I don't recognize the names of the devise methods which you
mentioned, so I'm assuming there were changes.
I'll have to look into the existing milia code to let you know the
expectation.

**Comment by dsaronin** [comment]
Kuno,
I've looked at the milia-specific code (gem itself). The only places that reference Devise callbacks appear to be in app/controllers/registrations_controller.rb, lines 122 to 138. But they merely continuing the (then at least) standard way to override devise methods.

But I suspect the issue with the either wrong or no email being generated, is really from milia usage & implementation instructions, notably in the sample app which I reference in the milia documentation and which the generator generates. This sample was provided as a way to show how to use milia and to help people see the correct way to implement milia. I just tried to transfer ownership of the github for the sample-milia-app to you, but you already have repository so named. I've also transferred the web-app-theme depository which is the template for the sample-milia-app.

Right now I don't see anywhere specific within sample-milia-app for designating mailer views, so it probably relies totally on the default view templates of devise, and it relies on Devise's default email callbacks. Older versions of milia did have to override Devise callbacks, but with the Rails 4 upgrade, that was no longer necessary.

You will have to dig within Devise itself to find what Devise is now expecting for a successful mail callback. What I always did to do that, is to go into where the Devise gem is installed (I always use Ruby Version Manager, rvm, so it's easy to do that), then I use ack-grep to globally search for terms related to what I'm trying to find.

Good luck.

**Comment by dsaronin** [comment]
PS: you may want to first look at any changes Devise has made to the expected parameter config file in config/initializers/devise.rb.
I suspect that newer versions of Devise may have made changed to expectations in this file.

**Comment by jekuno** [comment]
@runyourgym The master branch of milia now is dedicated to Rails 5. Could you please confirm the bug with the new Rails 5 sample app: https://github.com/jekuno/milia#sample-app

Regarding the flash[:notice]: You might have to do a `@user.reload` so that it knows the email before you display the flash message.

**Comment by jekuno** [comment]
@runyourgym I opened #68 regarding the issue with Rails5 + new devise version and already provided a fix for it in #69. Can you please confirm whether this fixes the issue for you as well?

**Comment by jekuno** [comment]
You can test this fix by adding the following line to your Gemfile: 
`gem 'milia', github: 'jekuno/milia', branch: 'issue#68'`

And then run `bundle install`.

**Comment by jekuno** [comment]
Released https://github.com/jekuno/milia/releases/tag/v1.3.1
Have fun!

**Comment by benvarien** [comment]
@epoplavskis I am learning Ruby On Rails now and I am having problems with rails 5. I tried to enter 
  rails g milia:install --org_email='do-not-reply@example.com'
to get milia started after putting 
  gem 'milia' 
on my Gemfile but I got this in response

/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :authenticate_tenant! has not been defined (ArgumentError)
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:637:in `each'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:637:in `block in skip_callback'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:568:in `block in __update_callbacks'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:566:in `reverse_each'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:566:in `__update_callbacks'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:636:in `skip_callback'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:212:in `block (3 levels) in <module:ClassMethods>'

and the list goes on for a while but I didn't want to fill this whole page up with what didn't load right. I was wondering how did you get milia to work on rails 5? What is gemspec? I am still learning how to use ruby on rails so I am new to all of this.

Thanks everyone!
Ben

**Comment by jekuno** [comment]
Do you have `before_action :authenticate_tenant!` in your `application_controller.rb` as described in https://github.com/jekuno/milia#application-controller?

**Comment by benvarien** [comment]
No, I have
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
end
But I'll give that a try, thanks!
I just try to follow steps on "The Complete Ruby on Rails Developer By Mashrur Hossain"

**Comment by marlungu** [comment]
@benvarien I had the same issue and resolved it by adding  **before_action: authenticate_tenant!** in  **application_controller.rb**. Then I changed the method from **before_filter** to **before_action** in **/config/initializers/devise_permitted_parameters.rb** and it worked just fine!

**Comment by PLSV** [comment]
@marlungu : Hey, Your solution worked!! Thanks a lot
