### ISSUE TITLE
Email address gets lost while inviting a new user

### ISSUE THREAD

**Issue by jekuno** [jekuno/milia#68]
**Observed**: With Rails5 and the new devise gem invitation emails don't get sent out to new users.

**Reason**: 
Try to send invitation via `user.save_and_invite_member`
=> calls `user.save` in `Milia::InviteMember`
=> runs `tenant.users << new_user` in `after_create` of `acts_as_universal_and_determines_account`
=> runs: `insert_record` from `ActiveRecord::Associations::HasManyThroughAssociation` which does a `user.save` thus updating the already saved user record with a new `updated_at` timestamp
=> triggers `before_update :postpone_email_change_until_confirmation_and_regenerate_confirmation_token, if: :postpone_email_change?` of devise (`postpone_email_change?` returns true) (also see https://github.com/plataformatec/devise/issues/2688)
=> the provided email address gets moved from attribute `email` to attribute `unconfirmed_email` by devise
=> the callback `after_commit :send_on_create_confirmation_instructions, on: :create, if: :send_confirmation_notification?` can't send the email because `email` attribute is blank

**Solution**:
* Set `@bypass_confirmation_postpone = true`  via `new_user.skip_reconfirmation!` in `after_create` of `acts_as_universal_and_determines_account`
* In turn `postpone_email_change?` returns false so that the provided email address doesn't get moved from attribute `email` to attribute `unconfirmed_email`
* The invitation mail gets sent out correctly

**Fix follows**

**Comment by dsaronin** [comment]
Excellent work figuring this out. It sounds like a change in behavior of
both devise and rails
