### ISSUE TITLE
Setting tenant with JWT.  Works with Thread.current_tenant?

### ISSUE THREAD

**Issue by goelinsights** [jekuno/milia#72]
@dsaronin was reading your gist on tokens
https://gist.github.com/dsaronin/8155622

Wondering if you had any suggestions for whether setting the tenant via a JWT token would cause any conflicts with the way you've designed milia (I have a SPA on the front end so tenant setting needs to be stateless which I believe makes the current session/ thread strategy become problematic if I want to ensure that data between tenants isn't accessible via rails as an api).  Could I set the token id from the tenant_user?

**Comment by dsaronin** [comment]
by "stateless" do you mean between http sessions & requests? If so, then
you should be saving the state, including the tenant, per the recommended
Rails procedure for saving/restoring state between requests. At the start
of each session, you'll need to restore the state, including setting the
Current_tenant via the prescribed milia procedures (which should be/used to
be in the Readme document). No other method should be used.

**Comment by jekuno** [comment]
Closing this as it's nearly 3 months old. Feel free to reopen if you still need support.
