### ISSUE TITLE
Milia gem installation problem

### ISSUE THREAD

**Issue by sparky369** [jekuno/milia#78]
I'm using rails in windows. 
After creating a new rails app
I include  gem 'devise' and  gem 'milia'   in gemfile.

then run   bundle install

In app/controllers/application_controller.rb add the following line immediately after protect_from_forgery:
before_action :authenticate_tenant!

I Run the following commands:

rails g milia:install --org_email='do-not-reply@example.com'

but it is not working. 
What can i do?
plz help. It's urgent.

**Comment by jekuno** [comment]
Please provide detailed information what isn't working.

Did you follow all steps precisely as described in https://github.com/jekuno/milia#sample-app?

**Comment by sparky369** [comment]
First, i created my rails app. Then after creating the app,  i add to my
Gemfile:
gem 'milia'
after that i run :
bundle install

In app/controllers/application_controller.rb   I add the following
line immediately
after protect_from_forgery:
before_action :authenticate_tenant! which is  given in screenshot. then i
run

rails g milia:install --org_email='mail@your-provider.de'
--skip_devise_generators=true

but it gives me the following error which is given in screenshot.

I don't understand what to do. plz help and give me step by step
instruction. I m using rails in windows and my installer was
railsinstaller 3.2.1.exe.  plz help me.

**Comment by jekuno** [comment]
Thanks for your answer. It looks as if you forgot to attach the screenshot showing the error?

**Comment by sparky369** [comment]
no.. I uploaded the attachment correctly but don't know why it is not
showing.

**Comment by sparky369** [comment]
however, here is the screenshot again.

**Comment by sparky369** [comment]
![screenshot 33](https://user-images.githubusercontent.com/30104803/28524296-a893dd86-70a1-11e7-8985-2131763aa6d8.png)
![screenshot 35](https://user-images.githubusercontent.com/30104803/28524295-a890ef18-70a1-11e7-87ed-b6cfededc9fd.PNG)
![screenshot 37](https://user-images.githubusercontent.com/30104803/28524294-a8906d2c-70a1-11e7-8ca1-97e17924215b.PNG)
![screenshot 39](https://user-images.githubusercontent.com/30104803/28524293-a88fc3b8-70a1-11e7-8d11-21a06b8b20a3.PNG)

**Comment by sparky369** [comment]
plz help me and provide direction as early as possible.

**Comment by sparky369** [comment]
plz sir, it's very urgent. plz reply me and help to solve this problem as soon as possible.

**Comment by jekuno** [comment]
This gem is maintained in free time for free so 24/7 support unfortunately cannot always be granted. ;)

However it seems as if Devise is missing - could you please send me your `Gemfile.lock`?

**Comment by sparky369** [comment]
thank u so much sir for your response. I understand 24/7 support is not possible always. i'm so sorry for my urgent help. however,  here is the gemfile.lock . Plz sir help me to solve this problem.

**Comment by sparky369** [comment]
[(zip) gemfileLock.zip](https://github.com/jekuno/milia/files/1176977/zip.gemfileLock.zip)

**Comment by jekuno** [comment]
Your `Gemfile.lock` looks sane. I run an app with exactly the same rails, milia and devise gem versions without any problems.

Maybe you have some misconfiguration of autoload_paths or missing a line such as `Bundler.require(*Rails.groups)` in `application.rb`?

**Comment by sparky369** [comment]
here is my screenshot for application.rb file..
![screenshot 34](https://user-images.githubusercontent.com/30104803/28632492-8fc8ebae-7252-11e7-9988-429f37ca168a.png)

**Comment by sparky369** [comment]
i'm new to rails.. plz give me some more direction what i should check to find out what the error could be..

**Comment by jekuno** [comment]
It seems as if it doesn't find Devise. You could try to add `require 'devise'` to the top of `application.rb` even though this usually shouldn't be needed.

**Comment by sparky369** [comment]
i did this. but now it gives me this error... here is the screenshot...

**Comment by sparky369** [comment]
![screenshot 35](https://user-images.githubusercontent.com/30104803/28673884-985823ee-7305-11e7-907b-fdb731e5e0e1.png)
![screenshot 36](https://user-images.githubusercontent.com/30104803/28673883-98439b40-7305-11e7-8230-2467bff447e0.png)
![screenshot 37](https://user-images.githubusercontent.com/30104803/28673881-9840311c-7305-11e7-833f-bd2562147dff.png)
![screenshot 38](https://user-images.githubusercontent.com/30104803/28673882-9842f17c-7305-11e7-8831-f03ddd903ba3.png)
![screenshot 39](https://user-images.githubusercontent.com/30104803/28673887-98c34b2e-7305-11e7-95c7-85e88f60d81a.png)
![screenshot 40](https://user-images.githubusercontent.com/30104803/28673885-986d2ab4-7305-11e7-80f8-22ad5d923d2c.png)

**Comment by sparky369** [comment]
I feel very helpless... this is not working correctly... Plz sir, give me all possible correction for which this error has occurred... should I update any configuration or something... plz sir help me...

**Comment by jekuno** [comment]
Please replace the milia line in your Gemfile with:
`gem 'milia', github: 'jekuno/milia', branch: 'issue#76'`
and run `bundle install` and then retry.
This also includes a milia update which changes the `before_filter` syntax to `before_action`.

**Comment by sparky369** [comment]
sir, I did this. but it now gives different error.. here is the screenshot...

**Comment by sparky369** [comment]
![screenshot 44](https://user-images.githubusercontent.com/30104803/28675222-0317ff6c-7309-11e7-82c7-eb7880193811.png)

**Comment by sparky369** [comment]
![screenshot 41](https://user-images.githubusercontent.com/30104803/28675248-18eecdac-7309-11e7-96e1-d157ccbf304d.png)
![screenshot 42](https://user-images.githubusercontent.com/30104803/28675246-18ed853c-7309-11e7-9730-9598a35bff9b.png)
![screenshot 43](https://user-images.githubusercontent.com/30104803/28675247-18ee7866-7309-11e7-8472-ac67be208906.png)

**Comment by jekuno** [comment]
`Unintialized constant Devise` is the same error you already posted above. What does your `application.rb` look like now?

Btw it would be better if you just paste the sources instead of adding screenshots. Otherwise this thread cannot be indexed by search engines properly and you can't copy & paste text.

**Comment by sparky369** [comment]
ok sir..  here is the zip file of my app..

**Comment by sparky369** [comment]
[sample_milia.zip](https://github.com/jekuno/milia/files/1180266/sample_milia.zip)

**Comment by jekuno** [comment]
I tested the app and running `rails g milia:install --org_email='do-not-reply@example.com'` worked out of the box. If you didn't use a rails template which runs the devise generators you may NOT add `--skip_devise_generators=true` of course.

I hope it works now as I cannot give any further support as of now.

**Comment by sparky369** [comment]
Thank u so much sir for your support. At last, it works fine.  I'm very grateful to you.

**Comment by jekuno** [comment]
:)

**Comment by sparky369** [comment]
sorry sir for bothering you again. i replace the milia line in my Gemfile in another project with:
gem 'milia', github: 'jekuno/milia', branch: 'issue#76
and run bundle install.
but it gives me the following error.. here is the screenshot..

**Comment by sparky369** [comment]
![screenshot 46](https://user-images.githubusercontent.com/30104803/28703714-b31c4a8e-7387-11e7-995b-75c282657585.png)
![screenshot 45](https://user-images.githubusercontent.com/30104803/28703715-b82935a0-7387-11e7-9ef6-adfb79f5d1ed.png)

**Comment by sparky369** [comment]
plz sir help me to solve this..

**Comment by sparky369** [comment]
sir.. plz give me direction what to do?

**Comment by sparky369** [comment]
plz sir, reply me... it's very urgent...
