### ISSUE TITLE
Can't install milia. plz help.

### ISSUE THREAD

**Issue by sparky369** [jekuno/milia#79]
i replace the milia line in my Gemfile in a project with:
gem 'milia', github: 'jekuno/milia', branch: 'issue#76'
and run bundle install.
but it gives me the following error.. 

Fetching https://github.com/jekuno/milia.git
fatal: Needed a single revision
Revision issue#76 does not exist in the repository
https://github.com/jekuno/milia.git. Maybe you misspelled it?

why it has occurred? plz help..

**Comment by sparky369** [comment]
plz, anybody help.. I really need the solution... Plz, help me...

**Comment by jekuno** [comment]
Try `gem install bundler` to update bundler and run `bundle install` again.

If this doesn't help use the following line in your Gemfile instead:
`gem 'milia', github: 'jekuno/milia', ref: '05b72dd'`

**Comment by sparky369** [comment]
thank u so much sir for ur help... 2nd method works fine... :)
