### ISSUE TITLE
Can't install on Rails 5.1.3

### ISSUE THREAD

**Issue by faisalhassanx** [jekuno/milia#81]
I'm still getting this error when I run the rails g milia:install command
```
```block in <module:DevisePermittedParameters>': undefined method `before_filter`' for DeviseController:Class
Did you mean?  before_action (NoMethodError)`
```

Ruby 2.4.1 & Rails 5.1.3

**Comment by jekuno** [comment]
Did you try my suggestion in https://github.com/jekuno/milia/issues/76#issuecomment-318091135 ?

**Comment by faisalhassanx** [comment]
Missed that. Thank you!
